// <auto-generated />
using System;
using Books.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Books.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201022112103_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Books.Database.Book", b =>
                {
                    b.Property<string>("Isbn")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Authour");

                    b.Property<string>("ThumbnailUrl");

                    b.Property<string>("Title");

                    b.Property<string>("Year");

                    b.HasKey("Isbn");

                    b.ToTable("Books");

                    b.HasData(
                        new { Isbn = "0553803700", Authour = " Robot\"", ThumbnailUrl = "http://books.google.com/books/content?id=QEhWPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", Title = "\"I", Year = "Isaac Asimov" },
                        new { Isbn = "0375913750", Authour = " Stargirl\"", ThumbnailUrl = "http://books.google.com/books/content?id=G9taxgEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api", Title = "\"Love", Year = "Jerry Spinelli" },
                        new { Isbn = "0743454553", Authour = "Jodi Picoult", ThumbnailUrl = "http://books.google.com/books/content?id=33Q_BAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api", Title = "Vanishing Acts", Year = "2005" },
                        new { Isbn = "0765317508", Authour = "Gary Jennings", ThumbnailUrl = "http://books.google.com/books/content?id=EGFHccTVhq8C&printsec=frontcover&img=1&zoom=1&source=gbs_api", Title = "Aztec", Year = "1980" },
                        new { Isbn = "0142501085", Authour = "Brian Jacques", Title = "Marlfox", Year = "1998" }
                    );
                });

            modelBuilder.Entity("Books.Database.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment");

                    b.Property<string>("Isbn");

                    b.Property<int?>("Rating");

                    b.Property<int>("UserId");

                    b.HasKey("ReviewId");

                    b.HasIndex("Isbn");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Books.Database.Review", b =>
                {
                    b.HasOne("Books.Database.Book")
                        .WithMany("Reviews")
                        .HasForeignKey("Isbn");
                });
#pragma warning restore 612, 618
        }
    }
}
